// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";
import { PrismaLibSql } from "@prisma/adapter-libsql";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? `file:${path.join(process.cwd(), "dev.db")}`,
    adapter: () => {
      const url =
        process.env["DATABASE_URL"] ?? `file:${path.join(process.cwd(), "dev.db")}`;
      const authToken = process.env["TURSO_AUTH_TOKEN"];
      return new PrismaLibSql({ url, ...(authToken ? { authToken } : {}) });
    },
  },
});
